package com.devmind.module.ai.llm;

import com.devmind.module.ai.vo.CitationResponse;
import com.devmind.module.search.vo.ChunkSearchResponse;
import org.springframework.stereotype.Component;

@Component
public class MockLlmClient implements LlmClient {

    @Override
    public boolean supports(String provider) {
        return "mock".equalsIgnoreCase(provider);
    }

    @Override
    public LlmResponse generate(LlmRequest request) {
        if (request.getRetrievedChunks().isEmpty()) {
            return new LlmResponse(
                    "I could not find relevant knowledge chunks for this question. Try adding more notes to the knowledge base.",
                    "mock-local",
                    true
            );
        }

        ChunkSearchResponse topChunk = request.getRetrievedChunks().get(0);
        StringBuilder answer = new StringBuilder();
        answer.append("Mock answer based on retrieved knowledge chunks.\n\n");
        answer.append("Question: ").append(request.getQuestion()).append("\n\n");
        answer.append("Key points:\n");
        answer.append("- The most relevant document is `")
                .append(topChunk.getDocumentTitle())
                .append("`.\n");
        answer.append("- The retrieved context mentions: ")
                .append(compact(topChunk.getContent()))
                .append("\n");
        answer.append("- This response is generated by MockLlmClient. ")
                .append("A real provider can replace this class without changing the RAG orchestration flow.\n\n");
        answer.append("Citations: ");
        for (int i = 0; i < request.getCitations().size(); i++) {
            CitationResponse citation = request.getCitations().get(i);
            if (i > 0) {
                answer.append(", ");
            }
            answer.append("chunkId=").append(citation.getChunkId());
        }

        return new LlmResponse(answer.toString(), "mock-local", true);
    }

    private String compact(String content) {
        String normalized = content.replace("\r\n", "\n")
                .replace("\r", "\n")
                .replace("\n", " ")
                .trim();
        if (normalized.length() <= 260) {
            return normalized;
        }
        return normalized.substring(0, 260) + "...";
    }
}
